"""Seed data for the storefront. Edit here or via the admin API to change product content."""

SITE_SETTINGS = {
    "key": "site",
    "brand_name": "LedgerKit",
    "tagline": "Practical Digital Guides",
    "support_email": "ledgerkitsupport@gmail.com",
    "support_phone": "",
    "business_address": "",
    "support_hours": "",
    "response_time": "",
}

CATEGORIES = [
    {"slug": "marketing", "name": "Marketing"},
    {"slug": "meta-ads", "name": "Meta Ads"},
    {"slug": "business", "name": "Business"},
    {"slug": "digital-products", "name": "Digital Products"},
    {"slug": "ai", "name": "AI"},
    {"slug": "productivity", "name": "Productivity"},
    {"slug": "templates", "name": "Templates"},
    {"slug": "guides", "name": "Guides"},
    {"slug": "health", "name": "Health & Reference"},
]

CURRICULUM = [
    {"part": "Part 1", "title": "Digital Product Research", "topics": [
        "Don't Build First — Research First",
        "Meta Ad Library — Your First Research Tool",
        "What to Observe Inside Meta Ad Library",
        "Reference vs Copy — Research Ethically",
        "How to Find 5–6 Potential Niches",
        "Digital Product Opportunity Scorecard",
        "From Research to Testing — Choose What to Test",
    ]},
    {"part": "Part 2", "title": "Build a Product People Want", "topics": [
        "Find a Worthy Problem",
        "Validate the Product Idea",
        "Define the Before → After Transformation",
        "Create Strong Product Value",
        "Make the Product Easy to Consume",
        "Design for Shareability",
        "Build a Strong Product Title & Hook",
        "Make the Product Memorable",
        "Launch With Momentum",
        "Build Real Social Proof",
        "Turn an Idea Into a Digital Product",
        "Product Creation Checklist — Problem → Value → Product",
    ]},
    {"part": "Part 3", "title": "AI-Assisted Product Creation", "topics": [
        "AI Is Your Assistant — Not Your Replacement",
        "AI Product Creation Workflow — Idea to Launch",
        "How to Write Better AI Prompts",
        "Use Visual References Without Copying",
        "Reference → Design Principles → Original Design",
        "Choosing the Right Product Format & Presentation",
    ]},
    {"part": "Part 4", "title": "Website & Sales Page", "topics": [
        "Why Your Sales Page Matters",
        "Landing Page Hero Section",
        "Problem → Solution Section",
        "What's Included + Product Preview",
        "Benefits + Real Proof",
        "Pricing + Bonus + FAQ + CTA",
        "Ad Promise → Landing Page Message Match",
        "Checkout, Mobile Experience & Trust",
    ]},
    {"part": "Part 5", "title": "Tracking", "topics": [
        "Meta Pixel — Tracking Basics",
        "Important Events — ViewContent, Lead, Checkout, Purchase",
        "Conversions API — Simple Explanation",
        "Pixel + CAPI + Event Deduplication",
        "Tracking Setup Checklist",
    ]},
    {"part": "Part 6", "title": "Creative Strategy", "topics": [
        "Show the Actual Product",
        "Creative Formats — Video, Static, Carousel, UGC, Screen Recording",
        "The First 3 Seconds — Why the Hook Matters",
        "Problem Hooks + Curiosity Hooks",
        "Demonstration + Mistake + Outcome + Objection Hooks",
        "Hook → Body → CTA",
        "One Body, Multiple Hooks",
        "Creative Concepts vs Creative Variations",
        "Creative Testing Matrix",
        "Placement-Native Creative",
        "Mobile-First Design + Safe Zones + Captions",
        "Ad Copy Structure",
        "Creative Testing Workflow",
    ]},
    {"part": "Part 7", "title": "Meta Ads Fundamentals", "topics": [
        "Campaign → Ad Set → Ad",
        "Meta Campaign Objectives Explained",
        "Why Sales Objective Makes Sense for Purchase Goals",
        "Meta Targeting Terminology — Interests, Not “Keywords”",
        "Audience Sources",
        "Broad vs Interest vs Lookalike",
        "Creative Can Also Act as Targeting",
        "Meta Automation in 2026",
        "Manual Control vs Automation",
        "ABO — Ad Set Budget",
        "Campaign Budget / Advantage Campaign Budget",
        "ABO vs CBO — Practical Framework, Not a Universal Rule",
        "Set Up Your First Test Campaign",
    ]},
    {"part": "Part 8", "title": "Practical Testing System", "topics": [
        "Testing Budget — Example, Not a Rule",
        "Audience / Targeting Hypotheses",
        "Creative Variations Per Ad Set",
        "What to Observe While Testing",
        "Meta Ads 101 Metrics Cheat Sheet — Part 1",
        "Meta Ads 101 Metrics Cheat Sheet — Part 2",
        "Metric Hierarchy — Attention → Click → Funnel → Purchase → Economics",
        "Campaign Diagnostic Flow",
        "Do Not Overreact to One Good or Bad Day",
        "Kill / Continue Decision Framework",
        "Stop Guessing — Test Hypotheses",
        "Change One Major Variable at a Time",
        "Campaign Testing Log",
        "How to Find Winners",
    ]},
    {"part": "Part 9", "title": "Winner Analysis & Scaling", "topics": [
        "Ad Set Winner vs Ad-Level Winner",
        "Vertical Scaling",
        "Horizontal Scaling",
        "Understanding the Learning Phase",
        "Fragmentation vs Consolidation",
        "Finding Your Scaling Ceiling",
        "Cost Cap — Advanced Bidding Strategy",
    ]},
    {"part": "Part 10", "title": "Retargeting & Creative Fatigue", "topics": [
        "Retargeting Funnel — Cold → Warm → Hot → Customer",
        "Custom Audiences for Retargeting",
        "Retargeting Creative Angles",
        "How to Spot Creative Fatigue",
        "Creative Refresh System",
    ]},
    {"part": "Part 11", "title": "Offer & Funnel Optimization", "topics": [
        "The Offer Equation",
        "Testing Different Offer Packages",
        "Where Are You Losing Buyers? — Funnel Diagnostics",
        "Landing Page Conversion & Checkout Completion",
        "Unit Economics — What One Order Really Earns",
        "Break-Even CPA",
        "AOV — Bundles, Order Bumps & Upsells",
        "Profitable Scale vs Highest ROAS",
        "Meta Reporting vs Real Money",
    ]},
    {"part": "Part 12", "title": "Business Measurement", "topics": [
        "Revenue Reconciliation — Meta vs Gateway vs Bank",
        "Attribution Basics",
        "Attributed Sales vs Incremental Sales",
        "Profitability vs Cash Flow",
        "Customer Value Ladder",
        "Backend Offers — Solve the Next Problem",
        "Meta Ad Rejection Prevention",
        "Landing Page Compliance",
    ]},
    {"part": "Part 13", "title": "Operating the Business", "topics": [
        "Campaign Naming System",
        "Weekly Ads Review System",
        "What I Got Wrong / What I Would Do Differently",
        "Beginner Roadmap",
        "Advanced Roadmap",
    ]},
    {"part": "Bonus", "title": "Bonus Toolkit", "topics": [
        "Bonus Toolkit Overview",
        "20 AI Prompts — Part 1",
        "20 AI Prompts — Part 2",
        "Hook Bank — 10 Problem Hooks",
        "Hook Bank — 10 Curiosity Hooks",
        "Hook Bank — 10 Demonstration Hooks",
        "Hook Bank — 10 Mistake Hooks",
        "Hook Bank — 10 Outcome Hooks",
        "Printable Creative Testing Matrix",
        "Printable Meta Metrics Cheat Sheet",
        "Printable Campaign Testing Log",
        "Pre-Launch Checklist",
        "Daily Ads Checklist",
        "Weekly Review Checklist",
        "Landing Page Checklist",
        "Product Validation Checklist",
        "Full Diagnostic Decision Tree",
        "Final Master Framework — Research to Expansion",
    ]},
    {"part": "Case Studies", "title": "Real Case Studies", "topics": [
        "Real Case Study — Campaign Setup Context",
        "Real Case Study — Ad Set Winners & Losers",
        "Real Case Study — Ad-Level Winner",
    ]},
    {"part": "Closing", "title": "Closing", "topics": [
        "Final Business Principles",
    ]},
]

SAMPLE_PAGES = [
    {"label": "Page 4", "title": "My First Research Tool — Meta Ad Library", "kind": "Chapter", "image": "/samples/page-ad-library.webp"},
    {"label": "Page 35", "title": "The 3-Second Hook — 6 Proven Hook Types", "kind": "Chapter", "image": "/samples/page-hooks.webp"},
    {"label": "Page 37", "title": "Build a Page-View Retargeting Campaign", "kind": "Framework", "image": "/samples/page-retargeting.webp"},
    {"label": "Page 45", "title": "Reading Ad Set Performance — Real Ads Manager Data", "kind": "Real Example", "image": "/samples/page-adset-performance.webp"},
    {"label": "Page 64", "title": "When an Ad Stops Working — Creative Fatigue Signals", "kind": "Chapter", "image": "/samples/page-creative-fatigue.webp"},
    {"label": "Page 114", "title": "Real Case Study — Ad-Level Winner", "kind": "Case Study", "image": "/samples/page-ad-winner.webp"},
]

# Starter testimonials — replace these with genuine customer reviews as they come in.
TESTIMONIALS = [
    {"product_slug": "meta-ads-decode", "customer_name": "Aarav M.", "review": "Finally a guide that connects product creation and ads into one system. The diagnostic flow alone stopped me from killing a good campaign too early.", "verified_purchase": False},
    {"product_slug": "meta-ads-decode", "customer_name": "Sneha R.", "review": "I understood more about CPA and unit economics in one evening than from months of random videos. The checklists stay open while I work.", "verified_purchase": False},
    {"product_slug": "meta-ads-decode", "customer_name": "Rohan K.", "review": "The case studies showing winners and losers made the concepts click. It reads like someone sharing their actual working notebook.", "verified_purchase": False},
]

PHYSICAL_GALLERY_SLOTS = []

META_ADS_DECODE_PRODUCT = {
    "slug": "meta-ads-decode",
    "title": "Digital Product Sales Engine",
    "short_title": "Sales Engine",
    "tagline": "The complete digital product sales system — research, create, launch and scale — with real Meta Ads campaigns inside.",
    "cover_image": "/samples/sales-engine-cover.webp",
    "combo_checkout_urls": {
        "ai-business-ideas-2026": "https://superprofile.bio/vp/6aabbbe69c594000137ba85a",
        "chatgpt-prompt-guide": "https://superprofile.bio/vp/6aabbae09c594000137b7a66"
    },
    "download_url": "https://customer-assets-39nsmqrw.emergentagent.net/job_guide-central-16/artifacts/y6e6znzi_Digital%20Product%20Mastery%20Decode%20Ebook.pdf",
    "description": (
        "A complete digital product guide covering the full journey — finding and validating product ideas, "
        "creating the product, building the sales page, setting up tracking, crafting creatives, and running "
        "Meta Ads with real campaign examples, testing, analysis and scaling. Built from practical workflows, "
        "real Ads Manager examples, frameworks, checklists and case studies collected over 3 years of hands-on experience."
    ),
    "category": "digital-products",
    "product_type": "Guide",
    "format": "Digital PDF",
    "delivery_method": "Instant digital access after successful payment",
    "cta_text": "Get Meta Ads Decode",
    "currency": "INR",
    "regular_price": 1699,
    "sale_price": 299,
    "pages_count": "135+ Core Pages + Case Studies",
    "featured": True,
    "is_new": True,
    "bestseller": False,
    "status": "published",
    "offer_end": None,
    "landing_path": "/meta-ads-decode",
    "experience_years": 3,
    "whats_included": [
        "Complete Meta Ads Decode Guide — 13 parts from research to business measurement",
        "Real case studies — campaign setup, ad-set winners & losers, ad-level winner",
        "Bonus toolkit — AI prompts, hook banks and printable resources",
        "Printable checklists — pre-launch, daily ads, weekly review, landing page, validation",
        "Printable frameworks — creative testing matrix, metrics cheat sheet, testing log",
        "Full diagnostic decision tree and master framework (research → expansion)",
    ],
    "key_benefits": [
        "Learn a complete system — not isolated tips",
        "Understand why decisions are made, not just what to do",
        "See concepts inside real campaign scenarios",
        "Diagnose campaigns with structured frameworks instead of guessing",
        "Understand real business economics — CPA, AOV, profitability, cash flow",
        "Reusable checklists and cheat sheets you can return to anytime",
    ],
    "bonuses": [
        "20 AI prompts for product creation",
        "Hook bank — 50 hooks across 5 categories",
        "Printable creative testing matrix",
        "Printable Meta metrics cheat sheet",
        "Printable campaign testing log",
        "Pre-launch, daily, weekly and landing-page checklists",
    ],
    "curriculum": CURRICULUM,
    "sample_pages": SAMPLE_PAGES,
    "physical_gallery_slots": PHYSICAL_GALLERY_SLOTS,
    "who_for": [
        {"title": "Students", "text": "Understand digital products, online business and Meta advertising through practical examples rather than only theory."},
        {"title": "Side-Income Explorers", "text": "Learn the system behind researching, creating, testing and marketing digital products before spending money on random ideas."},
        {"title": "Beginners in Digital Business", "text": "You have an idea but don't yet understand validation, websites, offers, creatives, advertising or tracking."},
        {"title": "Existing Product Sellers", "text": "You already sell ebooks, templates or courses and want a more structured testing and advertising system."},
        {"title": "Small Business Owners", "text": "You want to understand how Meta Ads, creatives, offers and landing pages work together."},
    ],
    "not_for": [
        "Not a “get rich quick” formula",
        "Not guaranteed campaign results",
        "Not a collection of random hacks",
        "Not a promise that one campaign structure works for everyone",
        "Not copied advertising creatives",
        "Not a substitute for testing in your own business",
    ],
    "faqs": [
        {"q": "Is this suitable for beginners?", "a": "Yes. Foundations are covered first — campaign structure, objectives, targeting and tracking — before the guide moves into testing systems, diagnostics and scaling."},
        {"q": "Does this guarantee profitable ads?", "a": "No. Advertising performance depends on your product, offer, market, creative, website, competition, pricing and many other factors. This guide is educational and results vary."},
        {"q": "Is this only about Meta Ads?", "a": "No. It covers the wider digital-product system — research, product development, website, tracking, creative strategy, advertising, funnel economics and business measurement."},
        {"q": "Is this a physical book?", "a": "No — this is a 100% digital product. You get instant online access after successful payment; nothing is shipped."},
        {"q": "How will I receive access?", "a": "Instantly. After successful payment confirmation you receive digital access through the configured delivery method (download page / email)."},
        {"q": "Does it contain practical examples?", "a": "Yes. The guide includes frameworks and campaign examples to explain decision-making, including case studies of campaign setup, ad-set winners & losers and an ad-level winner."},
        {"q": "Is Meta affiliated with this product?", "a": "No. This is an independent educational product and is not sponsored, endorsed or administered by Meta Platforms, Inc."},
    ],
    "editions": {
        "digital": {
            "label": "Digital Edition",
            "badge": "Instant Access",
            "price": 299,
            "cta": "Get Instant Access",
            "note": "Secure Checkout • Digital Product • Instant Access",
            "checkout_url": "https://superprofile.bio/vp/6aab089e0cce8b001386b6f9",
            "features": [
                "Complete Meta Ads Decode Guide — the full digital product system",
                "Digital PDF / ebook edition",
                "Read on phone, tablet or laptop",
                "Searchable digital format where supported",
                "Real Meta Ads campaign examples & case studies",
                "Bonus printable resources included",
            ],
        },
    },
}

AI_IDEAS_PRODUCT = {
    "slug": "ai-business-ideas-2026",
    "title": "AI Business Ideas Guide 2026",
    "short_title": "AI Ideas 2026",
    "cover_image": "/samples/ai-ideas-cover.webp",
    "download_url": "https://customer-assets-39nsmqrw.emergentagent.net/job_guide-central-16/artifacts/uz5kaujs_AI%20Business%20Ideas%20Guide%202026.pdf",
    "tagline": "Automation-ready AI business ideas you can start lean — with tools, workflows and monetization paths for each.",
    "description": "A practical guide to AI-powered business ideas for 2026 that run on automation. Each idea includes the tools stack, the workflow, and how it makes money — so you can pick one and start building instead of scrolling for inspiration.",
    "category": "ai",
    "product_type": "Guide",
    "format": "Digital PDF",
    "delivery_method": "Instant digital access after successful payment",
    "cta_text": "Get Instant Access",
    "currency": "INR",
    "regular_price": None,
    "sale_price": 199,
    "featured": False,
    "is_new": True,
    "bestseller": False,
    "status": "published",
    "offer_end": None,
    "whats_included": [
        "50+ AI business ideas for 2026",
        "Automation-first workflow for each idea",
        "Recommended tools stack per idea",
        "Monetization paths explained simply",
        "Beginner friendly — no coding needed",
    ],
    "key_benefits": [],
    "bonuses": [],
    "curriculum": [],
    "sample_pages": [],
    "who_for": [],
    "not_for": [],
    "faqs": [],
    "editions": {
        "digital": {
            "label": "Digital Edition",
            "badge": "Instant Access",
            "price": 199,
            "cta": "Get Instant Access",
            "note": "Secure Checkout • Digital Product • Instant Access",
            "checkout_url": "",
            "features": [],
        },
    },
}

PROMPT_GUIDE_PRODUCT = {
    "slug": "chatgpt-prompt-guide",
    "title": "ChatGPT Prompt Guide",
    "short_title": "Prompt Guide",
    "cover_image": "/samples/prompt-guide-cover.webp",
    "download_url": "https://customer-assets-39nsmqrw.emergentagent.net/job_guide-central-16/artifacts/gmhun7po_ChatGPT_Prompt_Guide_2026_Ledgerkit.pdf",
    "tagline": "Ready-to-use prompts for product research, ebook creation, landing page copy, hooks and ads.",
    "description": "A copy-paste prompt library for digital product builders. Covers product research, ebook creation, landing page copy, ad hooks and ad copy — the exact prompts that turn ChatGPT into a useful assistant instead of a generic content machine.",
    "category": "ai",
    "product_type": "Prompt Library",
    "format": "Digital PDF",
    "delivery_method": "Instant digital access after successful payment",
    "cta_text": "Get Instant Access",
    "currency": "INR",
    "regular_price": None,
    "sale_price": 149,
    "featured": False,
    "is_new": True,
    "bestseller": False,
    "status": "published",
    "offer_end": None,
    "whats_included": [
        "Product research & validation prompts",
        "Ebook creation prompts",
        "Landing page copy prompts",
        "Ad hook & ad copy prompts",
        "Copy-paste ready format",
    ],
    "key_benefits": [],
    "bonuses": [],
    "curriculum": [],
    "sample_pages": [],
    "who_for": [],
    "not_for": [],
    "faqs": [],
    "editions": {
        "digital": {
            "label": "Digital Edition",
            "badge": "Instant Access",
            "price": 149,
            "cta": "Get Instant Access",
            "note": "Secure Checkout • Digital Product • Instant Access",
            "checkout_url": "",
            "features": [],
        },
    },
}

BUNDLE_PRODUCT = {
    "slug": "complete-business-bundle",
    "title": "Complete Business Bundle",
    "short_title": "Business Bundle",
    "cover_image": "/samples/bundle-covers.webp",
    "tagline": "Digital Product Sales Engine + AI Business Ideas 2026 + ChatGPT Prompt Guide — the full stack in one purchase.",
    "description": "Everything you need to research, build, market and scale a digital product business: the complete Sales Engine guide, 50+ automation-ready AI business ideas, and the copy-paste ChatGPT prompt library — together at a bundle price.",
    "category": "business",
    "product_type": "Bundle",
    "format": "Digital PDF",
    "delivery_method": "Instant digital access after successful payment",
    "cta_text": "Get the Bundle",
    "currency": "INR",
    "regular_price": 647,
    "sale_price": 499,
    "featured": False,
    "is_new": True,
    "bestseller": False,
    "status": "published",
    "offer_end": None,
    "whats_included": [
        "Digital Product Sales Engine (₹299 value)",
        "AI Business Ideas Guide 2026 (₹199 value)",
        "ChatGPT Prompt Guide (₹149 value)",
        "Instant digital access to all three",
    ],
    "key_benefits": [],
    "bonuses": [],
    "curriculum": [],
    "sample_pages": [],
    "who_for": [],
    "not_for": [],
    "faqs": [],
    "editions": {
        "digital": {
            "label": "Complete Bundle",
            "badge": "Best Value",
            "price": 499,
            "cta": "Get Complete Bundle",
            "note": "Secure Checkout • Digital Products • Instant Access",
            "checkout_url": "https://superprofile.bio/vp/6aabaf99aa63460013c9c19f",
            "features": [],
        },
    },
}


SITE_BASE = "https://ledger-website.preview.emergentagent.com"

MEDICAL_BUNDLE_PRODUCT = {
    "slug": "medical-reference-bundle",
    "title": "Medical Diseases & Ayurvedic Reference Bundle",
    "short_title": "Medical Reference Bundle",
    "cover_image": "/samples/med-disease-cover.webp",
    "gallery": ["/samples/med-disease-cover.webp", "/samples/med-medicine-cover.webp"],
    "tagline": "Two illustrated reference guides in one bundle — a Diseases Reference Book and a Medicine Reference Guide, organised chapter-by-chapter for easy study and revision.",
    "description": (
        "A complete medical reference bundle for students, learners and the curious. The Diseases Reference Book "
        "walks through disease conditions and common clinical presentations — causes, features, assessment concepts "
        "and important considerations — in clear, colourful reference pages. The Medicine Reference Guide organises "
        "medicines into easy-to-browse categories with educational information at a glance. Both guides are designed "
        "for study, revision and general awareness, presented visually so information is easy to scan and remember."
    ),
    "category": "health",
    "product_type": "Bundle",
    "format": "Digital PDF (2 books)",
    "delivery_method": "Instant digital access after successful payment",
    "cta_text": "Get the Bundle",
    "currency": "INR",
    "regular_price": 1999,
    "sale_price": 199,
    "featured": False,
    "is_new": True,
    "bestseller": False,
    "status": "published",
    "offer_end": None,
    # Two files delivered together for this single purchase.
    "download_files": [
        {"title": "Diseases Reference Book", "url": f"{SITE_BASE}/downloads/diseases-reference-book.pdf"},
        {"title": "Medicine Reference Guide", "url": f"{SITE_BASE}/downloads/medicine-reference-guide.pdf"},
    ],
    "whats_included": [
        "Diseases Reference Book — conditions & clinical presentations (illustrated)",
        "Medicine Reference Guide — medicines organised by category",
        "Bilingual, easy-to-browse visual reference pages",
        "Instant digital access to both PDFs",
    ],
    "key_benefits": [
        "Study, revise and browse disease & medicine topics in one place",
        "Colourful, chapter-by-chapter layout designed for quick review",
        "For education and general awareness — not prescribing guidance",
    ],
    "bonuses": [],
    "curriculum": [],
    "sample_pages": [],
    "who_for": [
        {"title": "Students & learners", "text": "studying medical, health or Ayurvedic topics"},
        {"title": "Curious readers", "text": "who want a clear, illustrated reference to browse anytime"},
        {"title": "Educators", "text": "looking for a structured revision and awareness aid"},
    ],
    "not_for": [],
    "faqs": [
        {"q": "Is this medical advice?", "a": "No. Both guides are for education, study, revision and general awareness only. They are not a substitute for advice from a qualified healthcare professional and must not be used to start, stop or change any medicine."},
        {"q": "How do I receive the books?", "a": "Instantly. After successful payment you're taken to a download page with both PDFs, and the same links are emailed to you."},
        {"q": "What's inside the bundle?", "a": "Two digital PDF books — a Diseases Reference Book and a Medicine Reference Guide — delivered together in a single purchase."},
    ],
    "editions": {
        "digital": {
            "label": "Digital Bundle (2 Books)",
            "badge": "Instant Access",
            "price": 199,
            "cta": "Get Instant Access",
            "note": "Secure Checkout • Digital PDFs • Instant Access",
            "checkout_url": "",
            "features": [
                "Diseases Reference Book (PDF)",
                "Medicine Reference Guide (PDF)",
                "Instant download + emailed links",
            ],
        },
    },
}


_ADDON_FILES = {
    "ecg-guide": ("ECG Reading Guide", "/downloads/ECG_Reading_Guide.pdf"),
    "emergency-guide": ("Emergency Quick Reference Guide", "/downloads/Emergency_Quick_Reference_Guide.pdf"),
    "ayurvedic-medicine-guide": ("Ayurvedic Medicine Guide", "/downloads/Ayurvedic_Medicine_Guide.pdf"),
    "lab-report-guide": ("Lab Reports Decoded 2026", "/downloads/Lab-Reports-Decoded-2026.pdf"),
}


def _add_on(slug, title, price, tagline, description):
    """Hidden add-on guide: purchasable at checkout, excluded from store listings."""
    return {
        "slug": slug,
        "title": title,
        "short_title": title,
        "cover_image": "",
        "gallery": [],
        "tagline": tagline,
        "description": description,
        "category": "health",
        "product_type": "Add-on Guide",
        "format": "Digital PDF",
        "delivery_method": "Instant digital access after successful payment",
        "cta_text": "Add to Order",
        "currency": "INR",
        "regular_price": price,
        "sale_price": price,
        "featured": False,
        "is_new": False,
        "bestseller": False,
        "status": "published",
        "is_add_on": True,
        "offer_end": None,
        "download_files": [{"title": _f[0], "url": f"{SITE_BASE}{_f[1]}"} for _f in [_ADDON_FILES.get(slug)] if _f],
        "whats_included": [],
        "key_benefits": [],
        "bonuses": [],
        "curriculum": [],
        "sample_pages": [],
        "who_for": [],
        "not_for": [],
        "faqs": [],
        "editions": {
            "digital": {
                "label": "Digital PDF",
                "badge": "Add-on",
                "price": price,
                "cta": "Add to Order",
                "note": "Optional add-on • Digital PDF",
                "checkout_url": "",
                "features": [],
            },
        },
    }


ADD_ON_PRODUCTS = [
    _add_on(
        "ecg-guide", "ECG Guide", 99,
        "Read ECG strips with confidence — rate, rhythm & axis made simple, common abnormalities at a glance and quick-reference charts for revision.",
        "A quick-reference ECG guide covering rate, rhythm and axis interpretation, common abnormalities and revision charts. Educational reference only.",
    ),
    _add_on(
        "emergency-guide", "Emergency Guide", 149,
        "Emergency presentations and first-response information organised for quick revision — warning signs, red flags and what to check first.",
        "An emergency reference guide covering common emergency presentations, warning signs and first-response information in a quick-revision format. Educational reference only.",
    ),
    _add_on(
        "ayurvedic-medicine-guide", "Ayurvedic Medicine Guide", 99,
        "Common Ayurvedic medicines and remedies organised for easy educational reference — classical context, uses and precautions.",
        "An Ayurvedic medicine reference covering commonly referenced medicines and remedies with classical context, uses and precautions. Educational reference only — not prescribing guidance.",
    ),
    _add_on(
        "physiotherapy-clinical-guide", "Physiotherapy Clinical Guide", 149,
        "A clinical physiotherapy reference — assessment approaches, treatment plan concepts and home exercise programme ideas at a glance.",
        "A physiotherapy clinical reference covering assessment approaches, treatment plan concepts and home exercise programme ideas in a structured visual format. Educational reference only.",
    ),
    _add_on(
        "lab-report-guide", "Lab Report Guide", 99,
        "Understand common lab reports — what each marker means, typical reference ranges and why values matter, in plain language.",
        "A lab report reference explaining common lab markers, typical reference ranges and what values indicate, in plain language. Educational reference only.",
    ),
]

BOOKKEEPING_PRODUCT = {
    "slug": "business-bookkeeping-system",
    "title": "Business Bookkeeping Sheet System",
    "short_title": "Bookkeeping Sheet System",
    "cover_image": "/assets/bookkeeping/income.webp",
    "gallery": [
        "/assets/bookkeeping/setup.webp",
        "/assets/bookkeeping/monthly.webp",
        "/assets/bookkeeping/annual.webp",
        "/assets/bookkeeping/balance.webp",
        "/assets/bookkeeping/salestax.webp",
    ],
    "tagline": "One Excel file. Ten dashboards. Zero formulas to write.",
    "description": "Track income, expenses, profit & loss, taxes and monthly, quarterly & annual dashboards — all automatically, with clean graphs. Works in Excel or Google Sheets. Fully editable, auto-calculated, yours forever after a one-time payment.",
    "category": "templates",
    "product_type": "Excel Toolkit",
    "format": "Digital (Excel + Google Sheets)",
    "delivery_method": "Instant access after successful payment — file links + video tutorial delivered to your email",
    "cta_text": "Get lifetime access",
    "currency": "INR",
    "regular_price": 999,
    "sale_price": 290,
    "featured": False,
    "is_new": True,
    "bestseller": False,
    "status": "published",
    "is_add_on": False,
    "offer_end": None,
    "download_files": [
        {"title": "Business Bookkeeping System (Excel + Google Sheets + Video Tutorial)", "url": f"{SITE_BASE}/downloads/business-bookkeeping-system.pdf"},
    ],
    "whats_included": [
        "Income & expense tracker",
        "Auto profit & loss statement",
        "Monthly sales dashboard",
        "Quarterly & annual dashboards",
        "Tax summary calculator",
        "Ready-made graphs & charts",
        "Works in Excel & Google Sheets",
        "Fully editable · lifetime updates",
    ],
    "key_benefits": [
        "Auto-calculated — just type your numbers",
        "Works in Excel and Google Sheets",
        "Fully editable — your copy forever",
        "One-time payment · no subscription",
    ],
    "bonuses": [],
    "curriculum": [],
    "sample_pages": [
        "/assets/bookkeeping/income.webp",
        "/assets/bookkeeping/expenses.webp",
        "/assets/bookkeeping/monthly.webp",
        "/assets/bookkeeping/annual.webp",
        "/assets/bookkeeping/salestax.webp",
    ],
    "who_for": [],
    "not_for": [],
    "faqs": [
        {"question": "Do I need any special software?", "answer": "No. It's a spreadsheet that works in Google Sheets and Microsoft Excel. If you can open a spreadsheet, you can use this."},
        {"question": "Is it really fully editable?", "answer": "Yes. Change categories, colours, labels and formulas however you like. It's your copy forever."},
        {"question": "How do I receive the file after buying?", "answer": "The instant your payment succeeds we email your access to you, and it also appears right here to open — with your Google Sheets & Excel links plus a video tutorial."},
        {"question": "Is this a one-time payment?", "answer": "Absolutely. Pay ₹290 once via Razorpay and it's yours for life. No subscriptions, no recurring charges."},
        {"question": "Will my numbers calculate automatically?", "answer": "Yes. Just enter your income and expenses — profit & loss, taxes and every dashboard update themselves with graphs."},
    ],
    "editions": {
        "digital": {
            "label": "Lifetime Access",
            "badge": "Launch Price",
            "price": 290,
            "cta": "Get lifetime access",
            "note": "One-time payment · no subscription",
            "checkout_url": "",
            "features": [],
        },
    },
}

COMBO_PRODUCT = {
    "slug": "addons-combo-pack",
    "title": "All 5 Add-Ons Combo Pack",
    "short_title": "Add-Ons Combo Pack",
    "cover_image": "",
    "gallery": [],
    "tagline": "Every extra guide in one tick — all 5 add-on PDFs at the best price.",
    "description": "All five add-on guides (ECG, Emergency, Ayurvedic Medicine, Physiotherapy Clinical and Lab Report) bundled together at a special combo price. Educational reference only.",
    "category": "health",
    "product_type": "Add-on Combo",
    "format": "Digital PDF",
    "delivery_method": "Instant digital access after successful payment",
    "cta_text": "Add Combo to Order",
    "currency": "INR",
    "regular_price": 595,
    "sale_price": 299,
    "featured": False,
    "is_new": False,
    "bestseller": False,
    "status": "published",
    "is_add_on": True,
    "is_combo": True,
    "offer_end": None,
    "download_files": [
        {"title": "ECG Reading Guide", "url": f"{SITE_BASE}/downloads/ECG_Reading_Guide.pdf"},
        {"title": "Emergency Quick Reference Guide", "url": f"{SITE_BASE}/downloads/Emergency_Quick_Reference_Guide.pdf"},
        {"title": "Ayurvedic Medicine Guide", "url": f"{SITE_BASE}/downloads/Ayurvedic_Medicine_Guide.pdf"},
        {"title": "Lab Reports Decoded 2026", "url": f"{SITE_BASE}/downloads/Lab-Reports-Decoded-2026.pdf"},
    ],
    "whats_included": [],
    "key_benefits": [],
    "bonuses": [],
    "curriculum": [],
    "sample_pages": [],
    "who_for": [],
    "not_for": [],
    "faqs": [],
    "editions": {
        "digital": {
            "label": "All 5 Add-Ons",
            "badge": "Combo Price",
            "price": 299,
            "cta": "Add Combo to Order",
            "note": "Special combo price · Save ₹296",
            "checkout_url": "",
            "features": [],
        },
    },
}


MEDICAL_6_COMBO_PRODUCT = {
    "slug": "medical-6-pdf-combo",
    "title": "Ledgerkit 6 PDF Medical Combo",
    "short_title": "6 PDF Medical Combo",
    "cover_image": "/samples/combo-6/bundle-6-books.webp",
    "gallery": [
        "/samples/combo-6/bundle-6-books.webp",
        "/samples/combo-6/cover-disease.webp",
        "/samples/combo-6/cover-medicine.webp",
        "/samples/combo-6/cover-lab-report.webp",
        "/samples/combo-6/cover-emergency.webp",
        "/samples/combo-6/cover-ecg.webp",
        "/samples/combo-6/cover-ayurvedic.webp",
    ],
    "tagline": "Diseases, medicines, lab reports, emergencies, ECG and Ayurveda — six visual quick-reference guides in one instant download.",
    "description": (
        "Six practical medical quick-reference guides in one combo: Disease Reference (120+ conditions), "
        "Medicine Reference, Lab Report Decode (86 pages), Emergency Medical Guide (73 pages), ECG Reading "
        "Guide (59 pages) and Ayurvedic Medicine Guide (78 pages, English + Hindi). Visual diagrams, structured "
        "tables and easy-to-read pages built for study and revision on your phone, tablet or laptop. "
        "Educational reference only — not a prescription or treatment guide."
    ),
    "category": "health",
    "product_type": "Combo",
    "format": "Digital PDF (6 guides)",
    "delivery_method": "Instant digital access after successful payment — download links emailed to you",
    "cta_text": "Download all 6",
    "currency": "INR",
    "regular_price": 1699,
    "sale_price": 297,
    "featured": True,
    "is_new": True,
    "bestseller": False,
    "status": "published",
    "offer_end": None,
    "download_files": [
        {"title": "Disease Reference Guide", "url": f"{SITE_BASE}/downloads/diseases-reference-book.pdf"},
        {"title": "Medicine Reference Guide", "url": f"{SITE_BASE}/downloads/medicine-reference-guide.pdf"},
        {"title": "Lab Report Decode", "url": f"{SITE_BASE}/downloads/Lab-Reports-Decoded-2026.pdf"},
        {"title": "Emergency Medical Guide", "url": f"{SITE_BASE}/downloads/Emergency_Quick_Reference_Guide.pdf"},
        {"title": "ECG Reading Guide", "url": f"{SITE_BASE}/downloads/ECG_Reading_Guide.pdf"},
        {"title": "Ayurvedic Medicine Guide", "url": f"{SITE_BASE}/downloads/Ayurvedic_Medicine_Guide.pdf"},
    ],
    "whats_included": [
        "Disease Reference Guide — 120+ common diseases",
        "Medicine Reference Guide — drug class, uses, side effects",
        "Lab Report Decode — 86 pages",
        "Emergency Medical Guide — 73 pages",
        "ECG Reading Guide — 59 pages",
        "Ayurvedic Medicine Guide — 78 pages, English + Hindi",
    ],
    "key_benefits": [
        "Visual, quick-reference format for study and revision",
        "Instant PDF — read on mobile, tablet or laptop",
        "One-time payment — all 6 guides together",
    ],
    "bonuses": [],
    "curriculum": [],
    "sample_pages": [],
    "who_for": [
        {"title": "MBBS · BAMS · BHMS", "text": "students who want fast revision references"},
        {"title": "Nursing & Paramedical", "text": "students building clinical quick-reference skills"},
        {"title": "B.Pharm / D.Pharm & Interns", "text": "who need medicines, labs and ECG at a glance"},
    ],
    "not_for": [],
    "faqs": [
        {"q": "Is this a printed book?", "a": "No — these are instant PDF guides you can read on mobile, tablet and laptop."},
        {"q": "How will I get the PDFs?", "a": "Right after payment your download page opens instantly and the PDF links are delivered to your email."},
        {"q": "Who is it for?", "a": "MBBS, BAMS, BHMS, nursing, pharmacy (B.Pharm / D.Pharm), paramedical students and interns."},
        {"q": "Can I buy add-ons later?", "a": "No — add-ons can only be purchased together with the 6 PDF combo on this page."},
        {"q": "Refund policy?", "a": "These are digital products with instant access — no refunds once the PDFs are downloaded."},
        {"q": "Can I use it for treatment decisions?", "a": "No. These are educational quick-reference guides only — they do not replace textbooks, clinical training or a qualified doctor."},
    ],
    "editions": {
        "digital": {
            "label": "6 PDF Combo",
            "badge": "Launch Offer",
            "price": 297,
            "cta": "Download all 6",
            "note": "One-time payment • Instant PDF access",
            "checkout_url": "",
            "features": [
                "All 6 medical PDF guides",
                "Instant download + emailed links",
                "Mobile, tablet & laptop friendly",
            ],
        },
    },
}


_COMBO6_COVERS = {
    "ct-mri-xray-guide": "/samples/combo-6/cover-ct-scan.webp",
    "radiology-guide": "/samples/combo-6/cover-radiology.webp",
}


def _combo6_add_on(slug, title, tagline, description):
    """Add-on sold ONLY alongside the 6 PDF combo — hidden from every other listing."""
    doc = _add_on(slug, title, 149, tagline, description)
    doc["combo6_only"] = True
    doc["cover_image"] = _COMBO6_COVERS.get(slug, "")
    return doc


COMBO6_ADD_ON_PRODUCTS = [
    _combo6_add_on(
        "ct-mri-xray-guide", "CT Scan, MRI & X-Ray Guide",
        "Understand common imaging — what CT, MRI and X-Ray show, when each is used and how to read the basics.",
        "An imaging quick-reference covering CT scans, MRI and X-Rays — what each modality shows, common findings and how reports are structured. Educational reference only. PDF file pending upload.",
    ),
    _combo6_add_on(
        "radiology-guide", "Radiology Guide",
        "Radiology essentials for students — modalities, positioning basics and reading common studies.",
        "A radiology quick-reference for students covering imaging modalities, basic positioning and how to approach common studies. Educational reference only. PDF file pending upload.",
    ),
]
